markdown: kramdown
title: Destroying Computer
description: Why are you here?
theme: jekyll-theme-minimal

...
defaults:
  -
    scope:
      path: "posts"
      type: "pages"
    values:
      layout: "post"
      author: "sol"
      category: "posts"
...