markdown: kramdown
title: Destroying Computer
description: swag surfin 2 insterstellar planet
logo: /assets/img/cheabs2.jpg
theme: jekyll-theme-minimal

...
defaults:
  -
    scope:
      path: "posts"
      type: "pages"
    values:
      layout: "post"
      author: "7te"
      category: "posts"
...