markdown: kramdown
title: Destroying Computer
description: The only sure thing about luck is that it will change.
logo: /assets/img/cheabs2.jpg
theme: jekyll-theme-minimal
plugins: 
  - jekyll-coffeescript

...
defaults:
  -
    scope:
      path: "posts"
      type: "pages"
    values:
      layout: "post"
      author: "7te"
      category: "posts"
...